POST https://nodejs-crud-axfj.onrender.com/videos
Content-Type: application/json

{
  "title": "vídeo 03",
  "description": "Primeiro vídeo",
  "duration": 180
}

###

GET https://nodejs-crud-axfj.onrender.com/videos

###

PUT https://nodejs-crud-axfj.onrender.com/videos/
Content-Type: application/json

{
  "title": "vídeo 02",
  "description": "Primeiro vídeo",
  "duration": 180
}

###

DELETE https://nodejs-crud-axfj.onrender.com/videos/


